FROM ubuntu

WORKDIR /app

COPY package*.json ./

RUN apt update

RUN apt install python3-pip -y
RUN apt install ffmpeg -y

RUN apt install curl -y
RUN curl -sL https://deb.nodesource.com/setup_18.x | bash 
RUN apt install nodejs -y

RUN apt install build-essential -y
RUN apt install libcairo2-dev -y
RUN apt install libpango1.0-dev -y
RUN apt install libjpeg-dev -y
RUN apt install libgif-dev -y
RUN apt install librsvg2-dev -y

RUN apt update

RUN npm install

COPY . .

CMD ["npm", "start"]
